// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PersoApp.Models;

[Table("Employee")]
public partial class Employee
{
    [Key]
    public int EmployeeId { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Role { get; set; }

    public double Salary { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateOfEmployment { get ; set; }

    [Column("LocationID")]
    public int LocationId { get; set; }

    public double AbsenceInHours { get; set; }

    public double ScheduledHours { get; set; }

    [ForeignKey("LocationId")]
    [InverseProperty("Employees")]
    public virtual Location Location { get; set; }

    

}