// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PersoApp.Models;

[Table("Location")]
public partial class Location
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    public int Zipcode { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Country { get; set; }

    [InverseProperty("Location")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();
}